name: Validate PR

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  validation:
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    uses: ./.github/workflows/branch-validate.yml
